### ISSUE TITLE
Support for DS Fire Card dumping

### ISSUE THREAD

**Issue by m4x10187** [ApacheThunder/dsxTool#1]
Will there be any support for the DS Fire Card as well in the near future?

**Comment by ApacheThunder** [comment]
I do not currently own one. I am looking to acquire one though. Currently DLDI for these cards are not open source so it's unknown whether a tool like this will work for them.

Also unclear if someone manages to brick their card would be able to recover it. The slot2 usb device might still work but udisk nds file would have to be booted via a different flashcart first....and udisk may not boot correctly on what ever alt device you use it on.

**Comment by ApacheThunder** [comment]
Do you have the firmware files to that card? I was able to find DS Linker and N-Card firmware but not your's specifically.

Mainly want to look at udisk.nds....it appears udisk.nds is what the usb firmware update tool uses and the one for DS Linker anyways looks very similar to those rom dumps. It may be as simple as using a custom udisk.nds file but unless I see the firmware files for a DS Fire card I wouldn't know for sure.

**Comment by ApacheThunder** [comment]
Oh I just realized why you might be having issues getting GM9i to browse the N-Card. GM9i uses a limited set of embedded DLDI code/binaries when it's booted from DSi SD.

I built a custom version that forces NTR mode but with SD access enabled and I forced it to always use the DLDI bin patched into the SRL via fatInitDefault. For DSXtreme I have to launch this on the cart due to a quirk with how it's DLDI works.


But this might not be a thing with N-Card and it's clones. Regardless this custom build should work with your card in theory. I would be interested to know if it's able mount the card's filesystem from DSi mode. Assuming you have Unlaunch installed of coarse:

https://files.catbox.moe/bjbg54.ZIP

Let me know if that works. You will need to DLDI patch the NDS file with your card's DLDI. It should then work. But if not let me know. You can contact me on Discord and we can try and sort out the Gm9i support issue. ;)

I am on the DSI mode hacking server on Discord and can send you a invite link if you are not on it currently.

**Comment by ApacheThunder** [comment]
Ahh the freezing on mount. It happens with the DSX too. I had to put it on the DSX cart and boot it with NTR Launcher with SCFG unlocked before it would work.

**Comment by ApacheThunder** [comment]
Ok the DLDI init issue with DSX was resolved. Turned out that the DLDI code was relying on certain bits in the header to be set for it to work. We fixed it by hardcoding the card command bits related to that to always use the ones DSX expects.

Since Fire Card and clones don't have open source DLDI, I'm not sure if the same can be done to them. But knowing what part of the header sets the card commands. I updated the section of the header for the SRL related to that to match what the header from your dump used. (specifically the 16g cart but they both probably use same values here. Specifically the 0x60 region of the header)

Anyways here's one last build for you to try:

https://files.catbox.moe/vfkf17.zip

This one will run fatInitDefault instead of fatMountSimple. This will make it use the DLDI patched driver instead. For me this made DSX work. Maybe the case for you too. That's assuming System Menu applies the 0x60 bits to the cart even when not booting from the cart. (otherwise the DLDI code itself may need to reverse engineered to find if the same fix would apply to them and then make the needed changes)
